name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        gradle: [4.9, 4.10.2, 6.5.1]
        java: [jdk8, jdk11, jdk14]
        exclude: # Dont run older gradle versions on newer java
          - java: jdk14
            gradle: 4.9
          - java: jdk14
            gradle: 4.10.2
          - java: jdk14
            gradle: 5.6.4
          - java: jdk11
            gradle: 4.9
          - java: jdk11
            gradle: 4.10.2
    runs-on: ubuntu-20.04
    container:
      image: gradle:${{ matrix.gradle }}-${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: gradle build check test --stacktrace
